repository:
    description: Tools designed to make creating AWS Step Functions state machines simple and less error prone.
    homepage: https://rhodes.readthedocs.io/
    has_wiki: false

    default_branch: master
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: false

collaborators:
    -
        username: mattsb42-aws
        permission: admin

labels:
    -
        name: docs-update-required
        color: 62bf11

branches:
    -
        name: development
        protection:
            # Require at least one approving review on a pull request, before merging. Set to null to disable.
            required_pull_request_reviews: null
            # Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
            restrictions: null
            # Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
            enforce_admins: true
            # Require status checks to pass before merging. Set to null to disable
            required_status_checks:
                strict: true
                contexts:
                    - analysis (bandit)
    - name: master
      protection:
          # Require at least one approving review on a pull request, before merging. Set to null to disable.
          required_pull_request_reviews: null
          # Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
          restrictions: null
          # Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
          enforce_admins: true
          # Require status checks to pass before merging. Set to null to disable
          required_status_checks:
              # Require branches to be up to date before merging.
              strict: true
              # The list of status checks to require in order to merge into this branch.
              contexts:
                  # Static Analysis
                  - analysis (bandit)
                  # Linux
                  - tests (ubuntu-latest, 3.6, x64, local)
                  - tests (ubuntu-latest, 3.6, x64, examples)
                  - tests (ubuntu-latest, 3.7, x64, local)
                  - tests (ubuntu-latest, 3.7, x64, examples)
                  - tests (ubuntu-latest, 3.8, x64, local)
                  - tests (ubuntu-latest, 3.8, x64, examples)
                  - tests (ubuntu-latest, 3.x, x64, local)
                  - tests (ubuntu-latest, 3.x, x64, examples)
                  # MacOS
                  - tests (macos-latest, 3.6, x64, local)
                  - tests (macos-latest, 3.6, x64, examples)
                  - tests (macos-latest, 3.7, x64, local)
                  - tests (macos-latest, 3.7, x64, examples)
                  - tests (macos-latest, 3.8, x64, local)
                  - tests (macos-latest, 3.8, x64, examples)
                  - tests (macos-latest, 3.x, x64, local)
                  - tests (macos-latest, 3.x, x64, examples)
                  # Windows x86
                  - tests (windows-latest, 3.6, x86, local)
                  - tests (windows-latest, 3.6, x86, examples)
                  - tests (windows-latest, 3.7, x86, local)
                  - tests (windows-latest, 3.7, x86, examples)
                  - tests (windows-latest, 3.8, x86, local)
                  - tests (windows-latest, 3.8, x86, examples)
                  - tests (windows-latest, 3.x, x86, local)
                  - tests (windows-latest, 3.x, x86, examples)
                  # Windows x64
                  - tests (windows-latest, 3.6, x64, local)
                  - tests (windows-latest, 3.6, x64, examples)
                  - tests (windows-latest, 3.7, x64, local)
                  - tests (windows-latest, 3.7, x64, examples)
                  - tests (windows-latest, 3.8, x64, local)
                  - tests (windows-latest, 3.8, x64, examples)
                  - tests (windows-latest, 3.x, x64, local)
                  - tests (windows-latest, 3.x, x64, examples)
