name: automerge PRs

on:
    pull_request:
        types:
            - labeled
            - unlabeled
            - synchronize
            - opened
            - edited
            - ready_for_review
            - reopened
            - unlocked
    pull_request_review:
        types:
            - submitted

jobs:
    # Separate jobs to make sure that we don't merge to master from a branch named "development" on a fork
    automerge-to-development:
        if: github.base_ref == 'development'
        runs-on: ubuntu-latest
        steps:
            -   name: automerge
                uses: pascalgn/automerge-action@v0.6.1
                env:
                    GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
                    MERGE_LABELS: "!block merge"
                    MERGE_METHOD: squash
                    MERGE_COMMIT_MESSAGE: automatic
                    # Retry every 30s for 2h
                    MERGE_RETRIES: 240
                    MERGE_RETRY_SLEEP: 30000
    automerge-to-master:
        if: github.head_ref == 'development' && github.base_ref == 'master'
        runs-on: ubuntu-latest
        steps:
            -   name: automerge
                uses: pascalgn/automerge-action@v0.6.1
                env:
                    GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
                    MERGE_LABELS: automerge,!block merge
                    MERGE_METHOD: squash
                    MERGE_COMMIT_MESSAGE: automatic
                    # Don't auto-merge from forks
                    MERGE_FORKS: false
                    # Retry every 30s for 2h
                    MERGE_RETRIES: 240
                    MERGE_RETRY_SLEEP: 30000
