# This workflow takes any pull requests to maser and moves them to development.
name: pull request router

on:
    pull_request:
        branches:
            - master

jobs:
    send to development:
        # Move ay PRs to master that are not from development
        if: github.base_ref == 'master' && github.head_ref != 'development'
        runs-on: ubuntu-latest
        steps:
            -   name: switch branch
                uses: actions/github-script@v0.4.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        github.pulls.update({
                            owner: context.owner,
                            repo: context.repo,
                            pull_number: context.issue,
                            base: 'development'
                        })
            -   if: success()
                name: report
                uses: actions/github-script@v0.4.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        github.issues.createComment({
                            owner: context.owner,
                            repo: context.repo,
                            issue_number: context.issue,
                            body: 'Moving target to development branch.'
                        })
