name: Continuous Integration testing for Pull Requests

on: [pull_request]

jobs:
    analysis:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                stage:
                    - lint
                    - mypy
                    - bandit
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: check
              env:
                  TOXENV: ${{ matrix.stage }}
              run: tox -- -vv

    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                python:
                    - 3.6
                    - 3.7
                    - 3.8
                    - 3.x
                architecture:
                    - x64
                    - x86
                category:
                    - local
                    - examples
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: run test
              env:
                  TOXENV: ${{ matrix.category }}
              run: tox -- -vv
