name: Integration testing

on:
    pull_request:
        branches:
            - master

jobs:
    integ-tests:
        if: github.head_ref == 'development'
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
                python:
                    - 3.6
                    - 3.7
                    - 3.8
                    - 3.x
                architecture:
                    - x64
                    - x86
                category:
                    - integ
                # x86 builds are only meaningful for Windows
                exclude:
                    -   os: ubuntu-latest
                        architecture: x86
                    -   os: macos-latest
                        architecture: x86
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-python@v1
                with:
                    python-version: ${{ matrix.python }}
            -   uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.INTEG_AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.INTEG_AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-west-2
            -   run: |
                    python -m pip install --upgrade pip
                    pip install --upgrade -r ci-requirements.txt
            -   name: run test
                env:
                    TOXENV: ${{ matrix.category }}
                run: tox -- -vv
