name: Publish to PyPI

on:
    release:
        types: [published]

jobs:
    test-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: publish to test-PyPI
              env:
                  TOXENV: test-release
                  TEST_PYPI_SECRET_ARN: test-pypi-Evu7ev
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: us-west-2
              run: tox -- -vv
    release:
        needs: test-release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: publish to test-PyPI
              env:
                  TOXENV: release
                  PYPI_SECRET_ARN: secret:pypi-rhodes-LCCzlC
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: us-west-2
              run: tox -- -vv
