name: Publish to PyPI

on:
    release:
        types: [published]

jobs:
    test-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: publish to test-PyPI
              env:
                  TOXENV: test-release
                  TWINE_PASSWORD: ${{ secrets.TEST_PYPI }}
                  TEST_PYPI_SECRET_ARN: test-pypi
              run: tox -- -vv
    release:
        needs: test-release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.x
            - run: |
                python -m pip install --upgrade pip
                pip install --upgrade -r ci-requirements.txt
            - name: publish to test-PyPI
              env:
                  TOXENV: release
                  TWINE_PASSWORD: ${{ secrets.PYPI }}
                  PYPI_SECRET_ARN: pypi-rhodes
              run: tox -- -vv
