name: Apply repository settings

on:
    push:
        branches:
            - master
            - wat

jobs:
    apply-settings:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 2.x
            - name: apply settings
              uses: mattsb42/actions-settings@testing
              env:
                  GITHUB_TOKEN: ${{ secrets.SETTING_TOKEN }}
